#!/usr/bin/python

import RPi.GPIO as GPIO
import sys, os, re, time, fcntl

fd = sys.stdin.fileno()
fl = fcntl.fcntl(fd, fcntl.F_GETFL)
fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)

GPIO.setmode(GPIO.BOARD)
dtr = re.compile('.+TIOCM_DTR.+')
start = time.time()

print "AAAARRRRRRRRRG!!!"

def reset():
  pin = 7
  GPIO.setup(pin, GPIO.OUT)
  GPIO.output(pin, GPIO.HIGH)
  time.sleep(0.12)
  GPIO.output(pin, GPIO.LOW)

def process():
  print "Processing"
  while True:
    try:
#      print "I'm trying the process....."
      duration = time.time() - start
      input = sys.stdin.readline().strip()
      if dtr.match(input):
        reset()
        return
	time.sleep(0.1)
      elif duration > 500:
        return
        time.sleep(0.1)

    except:
      continue
      time.sleep(0.1)


process()
print "Accomplished with autoreset......  Finally!!"
GPIO.cleanup()
